name: Automação de Testes - api-easy-connect

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # ou a versão que você está usando

      - name: Install xk6
        run: |
          go install github.com/k6io/xk6/cmd/xk6@latest
          xk6 build --with github.com/szkiba/xk6-dotenv

      - name: Run k6 Tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          ./k6-automacao-api-easy-connect --env-file .env run scripts/easy-connect/colaborador/colaborador-post.js