name: Automação de Testes - api-easy-connect

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23' 

      - name: Install dependencies
        run: npm install

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Display environment variables for debugging
        run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" && echo "BASE_URL=${{ secrets.BASE_URL }}"

      - name: 'Create env file'
        run: |
          touch .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo API_TOKEN=${{ secrets.API_TOKEN }} >> .env
          cat .env

      - name: Run k6 tests
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./k6-automacao-api-easy-connect/scripts/easy-connect/colaborador/colaborador-post.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
