name: Automação de Testes - api-easy-connect

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load Environment Variables
        uses: crazy-max/ghaction-dotenv@v2
        with:
          env-file: config/.env 

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 tests
        run: k6 run ./k6-automacao-api-easy-connect/scripts/easy-connect/colaborador/colaborador-post.js
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
